### ISSUE TITLE
Support of Internet Explorer

### ISSUE THREAD

**Issue by OlivierChirouze** [OneKey-Network/OneKey-implementation#42]
Internet Explorer accounts for approx. 5% of the market today, and lacks support for a lot of JS libraries used in most projects.

Do we want to support it?

If so, we'll have to implement "polyfills" that can increase the size of the PAF libraries.

**Comment by broggeri** [comment]
>  5% of the market today
Source ? I had < 1% in mind.

I don't believe it will be necessary for the trial phases. We can review at V1 time.

**Comment by OlivierChirouze** [comment]
Weird: https://www.wpoven.com/blog/browser-market-share/, referring to statcounter, claims it's about 5%. While the statcounter website itself (https://gs.statcounter.com/browser-market-share) says about 10 times less (~ 0.5%).

I agree this is something we can leave out of the picture for MVP.

Thanks

**Comment by lbdvt** [comment]
Hi,

Good question, but Internet Explorer market share is very low and shrinking, it's likely to be on "old" devices (so negatively correlated to users purchasing power and sales), and Microsoft support will officially start ending on [June 15](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge) this year for some Windows versions. 

I think it's safe not to support it.
